/**
 * This file was automatically generated by OMG (OpenMicrofrontend Generator).
 * DO NOT MODIFY!
 */

import type { OpenMicrofrontendsRendererFunction } from "@open-microfrontends/types/OpenMicrofrontendsRendererFunction";

/* TypeScript type from Schemas */

export interface Microfrontend1Config {
  routePrefix: string;
}

/* --- Microfrontend 1 --- */

/* Type Parameters */

type Microfrontend1Permissions = undefined;

type Microfrontend1ApiProxyPaths = undefined;

type Microfrontend1MessagesPublish = undefined;
type Microfrontend1MessagesSubscribe = undefined;

/* Render Function */

export type Microfrontend1RenderFunction = OpenMicrofrontendsRendererFunction<
  Microfrontend1Config,
  Microfrontend1Permissions,
  Microfrontend1ApiProxyPaths,
  Microfrontend1MessagesPublish,
  Microfrontend1MessagesSubscribe
>;

export const Microfrontend1RenderFunctionName =
  "startBrowserStandaloneRoutingMicrofrontend1";
