/**
 * This file was automatically generated by OMG (OpenMicrofrontends Generator).
 * DO NOT MODIFY!
 */

import type { OpenMicrofrontendsRenderer } from '@open-microfrontends/types/OpenMicrofrontendsRenderer';

/* TypeScript type from Schemas */

export interface Microfrontend1Config {
  routePrefix: string;
}

/* --- Microfrontend 1 --- */

/* Type Parameters */

export type Microfrontend1Permissions = undefined;

type Microfrontend1ApiProxyPaths = undefined;

type Microfrontend1MessagesPublish = undefined;
type Microfrontend1MessagesSubscribe = undefined;

/* Renderer */

export type OpenMicrofrontendsExampleBrowserStandaloneRouting1Renderer = OpenMicrofrontendsRenderer<
  Microfrontend1Config,
  Microfrontend1Permissions,
  Microfrontend1ApiProxyPaths,
  Microfrontend1MessagesPublish,
  Microfrontend1MessagesSubscribe
>;

export const OpenMicrofrontendsExampleBrowserStandaloneRouting1RendererFunctionName =
  'startBrowserStandaloneRoutingMicrofrontend1';

/* Path constants */

export const OpenMicrofrontendsExampleBrowserStandaloneRouting1AssetsBasePath = '/';
