/* eslint-disable */
/**
* This file was automatically generated by OMG (OpenMicrofrontend Generator).
* DO NOT MODIFY!
*/

/* Config Types */
export interface Microfrontend1Config {
  /**
   * The customer ID
   */
  customerId: string;
  [k: string]: unknown;
}


/* Message Types */


type OpenMicrofrontendLifecycleHooks = {
    readonly onRemove?: () => void | Promise<void>;
};

type Partial<T> = {
    [P in keyof T]?: T[P];
};


// Render context for Microfrontend: OpenMicrofrontends Example API Proxy
type Microfrontend1Context = {
    // The unique ID of this Microfrontend instance
    readonly id: string;
    // Two-letter language code (e.g., "fr")
    readonly lang: string;
    readonly user: {
        readonly guest: boolean;
        readonly username: string;
        readonly displayName: string;
        
    },
    
    readonly apiProxyPaths: {
        
        readonly 'bff': string;
        
    },
    
    readonly config: Microfrontend1Config;
    
}


type Microfrontend1RenderCb = (hostElement: HTMLElement, context: Microfrontend1Context) => Promise<OpenMicrofrontendLifecycleHooks>;

// Render function for Microfrontend: OpenMicrofrontends Example API Proxy
export function onRenderOpenMicrofrontendsExampleAPIProxy(cb: Microfrontend1RenderCb): void {

    (window as any)['startMinimalApiProxyMicrofrontend'] = async (hostElement: HTMLElement, ...otherArgs: any[]) => {
        // Temporary Mashroom Server compatibility, until it supports OpenMicrofrontends natively
        const enableTempMashroomComp = otherArgs.length === 2 && otherArgs[0].appId && otherArgs[0].proxyPaths;

        const defaultContext: Omit<Microfrontend1Context, 'apiProxyPaths'> = {
            id: 'default',
            lang: 'en',
            user: {
                guest: true,
                username: 'guest',
                displayName: 'guest',
                
            },
            config: {
    "customerId": "1000"
},
            
        };

        let context: Microfrontend1Context;
        if (enableTempMashroomComp) {
            const {appId, lang, user, proxyPaths, appConfig} = otherArgs[0];
            const {messageBus} = otherArgs[1];
            context = {
                ...defaultContext,
                id: appId,
                lang,
                user,
                
                apiProxyPaths: proxyPaths,
                
                config: appConfig,
                
            };
        } else {
            // Default
            context = {
                ...defaultContext,
                ...otherArgs[0],
            };
        }

        // Validate
        
        if (!context.apiProxyPaths) {
            throw new Error('[OpenMicrofrontends] No apiProxyPaths provided!');
        }
        
        console.debug('[OpenMicrofrontends] Starting Microfrontend "OpenMicrofrontends Example API Proxy" with context:', context);
        const result = await cb(hostElement, context);

        if (enableTempMashroomComp) {
            return {
                willBeRemoved: result?.onRemove,
            };
        }
        return result;
    }
}

