/**
 * This file was automatically generated by OMG (OpenMicrofrontend Generator).
 * DO NOT MODIFY!
 */

import type { OpenMicrofrontendsClientContext } from "@open-microfrontends/types/OpenMicrofrontendsRendererFunction";

// Helper

function addCssLinkTag(url: string, addedElements: Array<HTMLElement>): void {
  const linkElem = document.createElement("link");
  linkElem.rel = "stylesheet";
  linkElem.href = url;
  linkElem.addEventListener("error", (error) => {
    console.error(
      "[OpenMicrofrontends] Error loading CSS resource: ",
      url,
      error,
    );
  });
  document.head.appendChild(linkElem);
  addedElements.push(linkElem);
}

function toFullUrl(...parts: Array<string>): string {
  return parts
    .map((part) => (part.endsWith("/") ? part.slice(0, -1) : part))
    .map((part, idx) =>
      idx > 0 && part && !part.startsWith("/") ? `/${part}` : part,
    )
    .join("");
}

/* TypeScript type from Schemas */

export interface Microfrontend1Config {
  routePrefix: string;
}

/* Type Parameters */

type Microfrontend1Permissions = undefined;

type Microfrontend1MessagesPublish = undefined;
type Microfrontend1MessagesSubscribe = undefined;

/* Type-safe MessageBus slice for the client */

/* Default config  */

const defaultConfig = {
  routePrefix: "",
};

/* Render function type with aligned config and message bus */

type Microfrontend1ClientContext = OpenMicrofrontendsClientContext<
  Partial<Microfrontend1Config>,
  Microfrontend1Permissions,
  undefined,
  Microfrontend1MessagesPublish,
  Microfrontend1MessagesSubscribe
>;

/* Start function */

export async function startOpenMicrofrontendsExampleBrowserStandaloneRouting2(
  serverUrl: string,
  hostElement: HTMLElement,
  context: Microfrontend1ClientContext,
) {
  const addedElements: Array<HTMLElement> = [];
  const exportedModules: Array<any> = [];

  // Add stylesheets

  addCssLinkTag(toFullUrl(serverUrl, "/", "Microfrontend2.css"), addedElements);

  const jsUrls = [toFullUrl(serverUrl, "/", "Microfrontend2.js")];

  // Load initial modules consecutively (ESM)
  try {
    for (const jsUrl of jsUrls) {
      const module = await import(jsUrl);
      if (module) {
        exportedModules.push(module);
      }
    }
  } catch (e) {
    console.error(
      '[OpenMicrofrontends] Loading assets of Microfrontend "OpenMicrofrontends Example Browser Standalone Routing 2" failed!',
      e,
    );
    throw new Error(
      '[OpenMicrofrontends] Loading assets of Microfrontend "OpenMicrofrontends Example Browser Standalone Routing 2" failed!',
    );
  }

  // Start Microfrontend
  const renderFunction =
    exportedModules.find(
      (m) => "startBrowserStandaloneRoutingMicrofrontend2" in m,
    )?.["startBrowserStandaloneRoutingMicrofrontend2"] ||
    exportedModules.find(
      (m) =>
        "default" in m &&
        "startBrowserStandaloneRoutingMicrofrontend2" in m.default,
    )?.default?.["startBrowserStandaloneRoutingMicrofrontend2"] ||
    (window as any)["startBrowserStandaloneRoutingMicrofrontend2"];
  if (!renderFunction) {
    throw new Error(
      '[OpenMicrofrontends] Render function of Microfrontend "OpenMicrofrontends Example Browser Standalone Routing 2" not found!',
    );
  }

  const contextWithDefaultConfig = {
    ...context,
    config: {
      ...defaultConfig,
      ...context.config,
    },
  };
  const lifecycleHooks = await renderFunction(
    hostElement,
    contextWithDefaultConfig,
  );

  return {
    close: async () => {
      console.info(
        '[OpenMicrofrontends] Closing Microfrontend "OpenMicrofrontends Example Browser Standalone Routing 2"',
      );
      await lifecycleHooks?.onRemove();
      addedElements.forEach((elem) => elem.remove());
      hostElement.innerHTML = "";
    },
  };
}
