/* eslint-disable */
/**
* This file was automatically generated by OMG (OpenMicrofrontend Generator).
* DO NOT MODIFY!
*/

/* Config Types */
    export interface Microfrontend1Config {
  welcomeMessage: string;
  [k: string]: unknown;
}


/* Message Types */
            export interface Microfrontend1TopicPing {
  ping: true;
  [k: string]: unknown;
}

    

type OpenMicrofrontendLifecycleHooks = {
    readonly onRemove?: () => void | Promise<void>;
};

type Partial<T> = {
    [P in keyof T]?: T[P];
};


// Helper

function loadJsResource(url: string, addedElements: Array<HTMLElement>): Promise<void> {
    return new Promise((resolve, reject) => {
        const scriptElem = document.createElement('script');
        scriptElem.src = url;
        if (url.endsWith('.mjs')) {
            scriptElem.type = 'module';
        }
        scriptElem.addEventListener('error', (error) => {
            console.error('[OpenMicrofrontends] Error loading JS resource: ', url, error);
            reject(error);
        });
        scriptElem.addEventListener('load', () => {
            resolve();
        });
        document.head.appendChild(scriptElem);
        addedElements.push(scriptElem);
    });
 }

function loadCssResource(url: string, addedElements: Array<HTMLElement>): void {
    const linkElem = document.createElement('link');
    linkElem.rel = 'stylesheet';
    linkElem.href = url;
    linkElem.addEventListener('error', (error) => {
        console.error('[OpenMicrofrontends] Error loading CSS resource: ', url, error);
    });
    document.head.appendChild(linkElem);
    addedElements.push(linkElem);
}

function toFullUrl(...parts: Array<string>): string {
    return parts
        .map((part) => part.endsWith('/') ? part.slice(0, -1) : part)
        .map((part, idx) => idx > 0 && part && !part.startsWith('/') ? `/${part}` : part)
        .join('');
}

    // Client context for Microfrontend: OpenMicrofrontends Example Minimal
type Microfrontend1Context = {
    // The unique ID of this Microfrontend instance
    readonly id?: string;
    // Two-letter language code (e.g., "fr")
    readonly lang?: string;
    readonly user?: {
        readonly guest: boolean;
        readonly username: string;
        readonly displayName: string;
        
    },
    
    readonly config: Partial<Microfrontend1Config>;
    
    readonly messageBus: {
        publish(topic: string, data: object): void;
        subscribe(topic: string, cb: (data: object) => void): void;
        unsubscribe(topic: string, cb: (data: object) => void): void;
    };
    
}

    

type Microfrontend1ClientMessageBus = {

    
    publish(topic: 'ping', data: Microfrontend1TopicPing): void;
    
    
    subscribe(topic: 'ping', cb: (data: Microfrontend1TopicPing) => void): void;
    unsubscribe(topic: 'ping', cb: (data: Microfrontend1TopicPing) => void): void;
    

};


    
// Start function for Microfrontend: OpenMicrofrontends Example Minimal
export async function startOpenMicrofrontendsExampleMinimal(serverUrl: string, hostElement: HTMLElement, context: Microfrontend1Context) {
    const addedElements: Array<HTMLElement> = [];

    // Load resources
    const jsPromises: Array<Promise<void>> = [
        
        loadJsResource(toFullUrl(serverUrl, '/', 'app1.mjs'), addedElements),
        
    ];
    

    try {
        await Promise.all(jsPromises);
    } catch (e) {
        console.error('[OpenMicrofrontends] Loading resources of Microfrontend "OpenMicrofrontends Example Minimal" failed!', e);
        return;
    }

    // Start Microfrontend
    const renderFunction = (window as any)['startMinimalMicrofrontend'];
    if (!renderFunction) {
        console.error('[OpenMicrofrontends] Render function of Microfrontend "OpenMicrofrontends Example Minimal" not found!');
        return;
    }

    

    const lifecycleHooks = await renderFunction(hostElement, context);

    return {
        close: async () => {
            console.info('[OpenMicrofrontends] Closing Microfrontend "OpenMicrofrontends Example Minimal"');
            await lifecycleHooks?.onRemove();
            addedElements.forEach((elem) => elem.remove());
            hostElement.innerHTML = '';
        },
        
        messages: context.messageBus as Microfrontend1ClientMessageBus,
        
    };
}

