/**
 * This file was automatically generated by OMG (OpenMicrofrontends Generator).
 * DO NOT MODIFY!
 */

import type { OpenMicrofrontendsClientContext } from '@open-microfrontends/types/OpenMicrofrontendsRendererFunction';

/* TypeScript type from Schemas */

export interface Microfrontend1Config {
  welcomeMessage: string;
  [k: string]: unknown;
}

export interface Microfrontend1TopicPing {
  ping: true;
  [k: string]: unknown;
}

// Helper

function toFullUrl(...parts: Array<string>): string {
  return parts
    .filter((part, idx) => part && part.trim() && (idx === 0 || part !== '/'))
    .map((part) => (part.endsWith('/') ? part.slice(0, -1) : part))
    .map((part, idx) => (idx > 0 && part.startsWith('/') ? part.substring(1) : part))
    .join('/');
}

function addCssLinkTag(url: string, addedElements: Array<HTMLElement>): void {
  const linkElem = document.createElement('link');
  linkElem.rel = 'stylesheet';
  linkElem.href = url;
  linkElem.addEventListener('error', (error) => {
    console.error('[OpenMicrofrontends] Error loading CSS resource: ', url, error);
  });
  document.head.appendChild(linkElem);
  addedElements.push(linkElem);
}

/* Asset query timestamp for cache busting */

const assetTimestamp = Math.floor(Date.now() / 10000) * 10;

/* Type Parameters */

type Microfrontend1Permissions = undefined;

type Microfrontend1MessagesPublish = Record<string, any>;
type Microfrontend1MessagesSubscribe = Record<string, any>;

/* Type-safe MessageBus slice for the client */

type Microfrontend1ClientMessageBus = {
  publish(topic: 'ping', data: Microfrontend1TopicPing): void;

  subscribe(topic: 'ping', cb: (data: Microfrontend1TopicPing) => void): void;
  unsubscribe(topic: 'ping', cb: (data: Microfrontend1TopicPing) => void): void;
};

/* Default config  */

const defaultConfig = {
  welcomeMessage: 'Hello World!',
};

/* Render function type with aligned config and message bus */

type Microfrontend1ClientContext = Omit<
  OpenMicrofrontendsClientContext<
    Partial<Microfrontend1Config>,
    Microfrontend1Permissions,
    undefined,
    Microfrontend1MessagesPublish,
    Microfrontend1MessagesSubscribe
  >,
  'apiProxyPaths' | 'serverSideRendered'
>;

/* Start function */

export async function startOpenMicrofrontendsExampleBrowserStandaloneCodeSplitting(
  serverUrl: string,
  hostElement: HTMLElement,
  context: Microfrontend1ClientContext
) {
  const addedElements: Array<HTMLElement> = [];
  const exportedModules: Array<any> = [];

  // Add stylesheets

  addCssLinkTag(toFullUrl(serverUrl, '/', `Microfrontend.css?v=${assetTimestamp}`), addedElements);

  const jsUrls = [toFullUrl(serverUrl, '/', `Microfrontend.js?v=${assetTimestamp}`)];

  // Load initial modules consecutively (ESM)
  try {
    for (const jsUrl of jsUrls) {
      const module = await import(jsUrl);
      if (module) {
        exportedModules.push(module);
      }
    }
  } catch (e) {
    throw new Error(
      '[OpenMicrofrontends] Loading assets of Microfrontend "OpenMicrofrontends Example Browser Standalone Code Splitting" failed!'
    );
  }

  const renderFunction =
    exportedModules.find((m) => 'startBrowserStandaloneCodeSplittingMicrofrontend' in m)?.[
      'startBrowserStandaloneCodeSplittingMicrofrontend'
    ] ||
    exportedModules.find((m) => 'default' in m && 'startBrowserStandaloneCodeSplittingMicrofrontend' in m.default)
      ?.default?.['startBrowserStandaloneCodeSplittingMicrofrontend'] ||
    (window as any)['startBrowserStandaloneCodeSplittingMicrofrontend'];
  if (!renderFunction) {
    throw new Error(
      '[OpenMicrofrontends] Render function of Microfrontend "OpenMicrofrontends Example Browser Standalone Code Splitting" not found!'
    );
  }

  const contextWithDefaultConfig = {
    ...context,
    config: {
      ...defaultConfig,
      ...context.config,
    },
  };

  // Render the Microfrontend
  console.info(
    '[OpenMicrofrontends] Starting Microfrontend "OpenMicrofrontends Example Browser Standalone Code Splitting"'
  );
  const lifecycleHooks = await renderFunction(hostElement, contextWithDefaultConfig);

  return {
    close: async () => {
      console.info(
        '[OpenMicrofrontends] Closing Microfrontend "OpenMicrofrontends Example Browser Standalone Code Splitting"'
      );
      await lifecycleHooks?.onRemove();
      addedElements.forEach((elem) => elem.remove());
      hostElement.innerHTML = '';
    },

    messages: context.messageBus as Microfrontend1ClientMessageBus,
  };
}
