/**
 * This file was automatically generated by OMG (OpenMicrofrontends Generator).
 * DO NOT MODIFY!
 */

import type { OpenMicrofrontendsClientContext } from '@open-microfrontends/types/OpenMicrofrontendsRenderer';

/* TypeScript type from Schemas */

export interface Microfrontend1Config {
  /**
   * The customer ID
   */
  customerId: string;
  [k: string]: unknown;
}

// Helper

function toFullUrl(...parts: Array<string>): string {
  return parts
    .filter((part, idx) => part && part.trim() && (idx === 0 || part !== '/'))
    .map((part) => (part.endsWith('/') ? part.slice(0, -1) : part))
    .map((part, idx) => (idx > 0 && part.startsWith('/') ? part.substring(1) : part))
    .join('/');
}

function addCssLinkTag(url: string, addedElements: Array<HTMLElement>): void {
  const linkElem = document.createElement('link');
  linkElem.rel = 'stylesheet';
  linkElem.href = url;
  linkElem.addEventListener('error', (error) => {
    console.error('[OpenMicrofrontends] Error loading CSS resource: ', url, error);
  });
  document.head.appendChild(linkElem);
  addedElements.push(linkElem);
}

/*
 * The setup calculated by the Host Application backend
 */
type HostBackendMicrofrontendSetup = Pick<
  OpenMicrofrontendsClientContext<any, any, any, any, any>,
  'lang' | 'user' | 'permissions' | 'hostContext'
> & {
  readonly assetBuildTimestampOrVersion?: string;
  readonly rewrittenImportMaps?: {
    readonly imports: Record<string, string>;
  };
};

const omBasePath = '/__om__';
const omAssetsSubPath = '/assets';
const omProxiesSubPath = '/proxies';
const omSetupSubPath = '/setup';

const fallbackAssetTimestamp = Math.floor(Date.now() / 10000) * 10;

/* Type Parameters */

type Microfrontend1MessagesPublish = undefined;
type Microfrontend1MessagesSubscribe = undefined;

/* Type-safe MessageBus slice for the client */

/* Default config  */

const defaultConfig = {
  customerId: '1000',
};

/* Renderer context type with aligned config and message bus */

type Microfrontend1ClientContext = Omit<
  OpenMicrofrontendsClientContext<
    Partial<Microfrontend1Config>,
    undefined,
    undefined,
    Microfrontend1MessagesPublish,
    Microfrontend1MessagesSubscribe
  >,
  'apiProxyPaths' | 'permissions' | 'user'
>;

/* Microfrontend setup */

const getHostBackendMicrofrontendSetup = async (id: string, name: string): Promise<HostBackendMicrofrontendSetup> => {
  const preloadedSetup = window[`__om__setup__${name}_${id}`];
  if (preloadedSetup) {
    return preloadedSetup;
  }
  try {
    const response = await fetch(`${omBasePath}/${name}${omSetupSubPath}`);
    return await response.json();
  } catch (e) {
    console.error(
      `[OpenMicrofrontends] Loading setup of Microfrontend ${name} failed. Did you add the necessary Host Integration?`,
      e
    );
    throw new Error(`[OpenMicrofrontends] Loading setup of Microfrontend ${name} failed!`);
  }
};

/* Start function */

export async function startOpenMicrofrontendsExampleAPIProxyWithSecurity(
  hostElement: HTMLElement,
  context: Microfrontend1ClientContext
) {
  const addedElements: Array<HTMLElement> = [];
  const exportedModules: Array<any> = [];
  const assetsPath = `${omBasePath}/OpenMicrofrontendsExampleAPIProxyWithSecurity${omAssetsSubPath}`;
  const proxiesPath = `${omBasePath}/OpenMicrofrontendsExampleAPIProxyWithSecurity${omProxiesSubPath}`;
  const setup = await getHostBackendMicrofrontendSetup(context.id, 'OpenMicrofrontendsExampleAPIProxyWithSecurity');
  const { assetBuildTimestampOrVersion, rewrittenImportMaps, ...serverContext } = setup;
  const serverSideRendered = !!window[`__om_ssr_OpenMicrofrontendsExampleAPIProxyWithSecurity_${context.id}__`];

  if (serverSideRendered) {
    console.info(
      '[OpenMicrofrontends] Found server-side rendered Microfrontend "OpenMicrofrontends Example API Proxy with Security"'
    );
  }

  const jsUrls = [
    toFullUrl(assetsPath, `Microfrontend.js?v=${assetBuildTimestampOrVersion ?? fallbackAssetTimestamp}`),
  ];

  // Load initial modules consecutively (ESM)
  try {
    for (const jsUrl of jsUrls) {
      const module = await import(jsUrl);
      if (module) {
        exportedModules.push(module);
      }
    }
  } catch (e) {
    throw new Error(
      '[OpenMicrofrontends] Loading assets of Microfrontend "OpenMicrofrontends Example API Proxy with Security" failed!'
    );
  }

  const renderFunction =
    exportedModules.find((m) => 'startApiProxySecurityMicrofrontend' in m)?.['startApiProxySecurityMicrofrontend'] ||
    exportedModules.find((m) => 'default' in m && 'startApiProxySecurityMicrofrontend' in m.default)?.default?.[
      'startApiProxySecurityMicrofrontend'
    ] ||
    (window as any)['startApiProxySecurityMicrofrontend'];
  if (!renderFunction) {
    throw new Error(
      '[OpenMicrofrontends] Renderer of Microfrontend "OpenMicrofrontends Example API Proxy with Security" not found!'
    );
  }

  const apiProxyPaths = {};

  apiProxyPaths['bff'] = `${proxiesPath}/bff`;

  apiProxyPaths['chuckNorrisJoke'] = `${proxiesPath}/chuckNorrisJoke`;

  const contextWithDefaultConfig = {
    ...serverContext,
    ...context,
    apiProxyPaths,
    serverSideRendered,
    config: {
      ...defaultConfig,
      ...context.config,
    },
  };

  // Render the Microfrontend
  console.info('[OpenMicrofrontends] Starting Microfrontend "OpenMicrofrontends Example API Proxy with Security"');
  const lifecycleHooks = await renderFunction(hostElement, contextWithDefaultConfig);

  return {
    close: async () => {
      console.info('[OpenMicrofrontends] Closing Microfrontend "OpenMicrofrontends Example API Proxy with Security"');
      await lifecycleHooks?.onRemove();
      addedElements.forEach((elem) => elem.remove());
      hostElement.innerHTML = '';
    },
  };
}
