/**
 * This file was automatically generated by OMG (OpenMicrofrontend Generator).
 * DO NOT MODIFY!
 */

import type { OpenMicrofrontendsClientContext } from "@open-microfrontends/types/OpenMicrofrontendsRendererFunction";

// Helper

function addCssLinkTag(url: string, addedElements: Array<HTMLElement>): void {
  const linkElem = document.createElement("link");
  linkElem.rel = "stylesheet";
  linkElem.href = url;
  linkElem.addEventListener("error", (error) => {
    console.error(
      "[OpenMicrofrontends] Error loading CSS resource: ",
      url,
      error,
    );
  });
  document.head.appendChild(linkElem);
  addedElements.push(linkElem);
}

function toFullUrl(...parts: Array<string>): string {
  return parts
    .map((part) => (part.endsWith("/") ? part.slice(0, -1) : part))
    .map((part, idx) =>
      idx > 0 && part && !part.startsWith("/") ? `/${part}` : part,
    )
    .join("");
}

/* TypeScript type from Schemas */

export interface Microfrontend1Config {
  welcomeMessage: string;
  [k: string]: unknown;
}

export interface Microfrontend1TopicPing {
  ping: true;
  [k: string]: unknown;
}

/* Asset query timestamp for cache busting */

const assetTimestamp = Math.floor(Date.now() / 10000) * 10;

/* Type Parameters */

type Microfrontend1Permissions = undefined;

type Microfrontend1MessagesPublish = Record<string, any>;
type Microfrontend1MessagesSubscribe = Record<string, any>;

/* Type-safe MessageBus slice for the client */

type Microfrontend1ClientMessageBus = {
  publish(topic: "ping", data: Microfrontend1TopicPing): void;

  subscribe(topic: "ping", cb: (data: Microfrontend1TopicPing) => void): void;
  unsubscribe(topic: "ping", cb: (data: Microfrontend1TopicPing) => void): void;
};

/* Default config  */

const defaultConfig = {
  welcomeMessage: "Hello World!",
};

/* Render function type with aligned config and message bus */

type Microfrontend1ClientContext = OpenMicrofrontendsClientContext<
  Partial<Microfrontend1Config>,
  Microfrontend1Permissions,
  undefined,
  Microfrontend1MessagesPublish,
  Microfrontend1MessagesSubscribe
>;

/* Start function */

export async function startOpenMicrofrontendsExampleBrowserStandaloneHelloWorld(
  serverUrl: string,
  hostElement: HTMLElement,
  context: Microfrontend1ClientContext,
) {
  const addedElements: Array<HTMLElement> = [];
  const exportedModules: Array<any> = [];

  const jsUrls = [
    toFullUrl(serverUrl, "/", `Microfrontend.js?v=${assetTimestamp}`),
  ];

  // Load initial modules consecutively (ESM)
  try {
    for (const jsUrl of jsUrls) {
      const module = await import(jsUrl);
      if (module) {
        exportedModules.push(module);
      }
    }
  } catch (e) {
    console.error(
      '[OpenMicrofrontends] Loading assets of Microfrontend "OpenMicrofrontends Example Browser Standalone Hello World" failed!',
      e,
    );
    throw new Error(
      '[OpenMicrofrontends] Loading assets of Microfrontend "OpenMicrofrontends Example Browser Standalone Hello World" failed!',
    );
  }

  // Start Microfrontend
  const renderFunction =
    exportedModules.find(
      (m) => "startBrowserStandaloneHelloWorldMicrofrontend" in m,
    )?.["startBrowserStandaloneHelloWorldMicrofrontend"] ||
    exportedModules.find(
      (m) =>
        "default" in m &&
        "startBrowserStandaloneHelloWorldMicrofrontend" in m.default,
    )?.default?.["startBrowserStandaloneHelloWorldMicrofrontend"] ||
    (window as any)["startBrowserStandaloneHelloWorldMicrofrontend"];
  if (!renderFunction) {
    throw new Error(
      '[OpenMicrofrontends] Render function of Microfrontend "OpenMicrofrontends Example Browser Standalone Hello World" not found!',
    );
  }

  const contextWithDefaultConfig = {
    ...context,
    config: {
      ...defaultConfig,
      ...context.config,
    },
  };
  const lifecycleHooks = await renderFunction(
    hostElement,
    contextWithDefaultConfig,
  );

  return {
    close: async () => {
      console.info(
        '[OpenMicrofrontends] Closing Microfrontend "OpenMicrofrontends Example Browser Standalone Hello World"',
      );
      await lifecycleHooks?.onRemove();
      addedElements.forEach((elem) => elem.remove());
      hostElement.innerHTML = "";
    },

    messages: context.messageBus as Microfrontend1ClientMessageBus,
  };
}
