/**
 * This file was automatically generated by OMG (OpenMicrofrontend Generator).
 * DO NOT MODIFY!
 */

import type { OpenMicrofrontendsRendererFunction } from "@open-microfrontends/types/OpenMicrofrontendsRendererFunction";

/* TypeScript type from Schemas */

export interface Microfrontend1Config {
  /**
   * The customer ID
   */
  customerId: string;
  [k: string]: unknown;
}

/* --- Microfrontend 1 --- */

/* Type Parameters */

type Microfrontend1Permissions = undefined;

type Microfrontend1ApiProxyPaths = {
  readonly bff: string;

  readonly chuckNorrisJoke: string;
};

type Microfrontend1MessagesPublish = undefined;
type Microfrontend1MessagesSubscribe = undefined;

/* Render Function */

export type OpenMicrofrontendsExampleAPIProxyWithSecurityRenderFunction =
  OpenMicrofrontendsRendererFunction<
    Microfrontend1Config,
    Microfrontend1Permissions,
    Microfrontend1ApiProxyPaths,
    Microfrontend1MessagesPublish,
    Microfrontend1MessagesSubscribe
  >;

export const OpenMicrofrontendsExampleAPIProxyWithSecurityRenderFunctionName =
  "startApiProxySecurityMicrofrontend";
