/**
 * This file was automatically generated by OMG (OpenMicrofrontend Generator).
 * DO NOT MODIFY!
 */

import type { OpenMicrofrontendsRendererFunction } from "@open-microfrontends/types/OpenMicrofrontendsRendererFunction";

/* TypeScript type from Schemas */

export interface Microfrontend1Config {
  welcomeMessage: string;
  [k: string]: unknown;
}

export interface Microfrontend1TopicPing {
  ping: true;
  [k: string]: unknown;
}

/* --- Microfrontend 1 --- */

/* Type Parameters */

type Microfrontend1Permissions = undefined;

type Microfrontend1ApiProxyPaths = undefined;

type Microfrontend1MessagesPublish = {
  ping: Microfrontend1TopicPing;
};
type Microfrontend1MessagesSubscribe = {
  ping: Microfrontend1TopicPing;
};

/* Render Function */

export type Microfrontend1RenderFunction = OpenMicrofrontendsRendererFunction<
  Microfrontend1Config,
  Microfrontend1Permissions,
  Microfrontend1ApiProxyPaths,
  Microfrontend1MessagesPublish,
  Microfrontend1MessagesSubscribe
>;

export const Microfrontend1RenderFunctionName =
  "startBrowserStandaloneSharedLibrariesMicrofrontend2";
