/**
 * This file was automatically generated by OMG (OpenMicrofrontends Generator).
 * DO NOT MODIFY!
 */

import type { OpenMicrofrontendsClientContext } from '@open-microfrontends/types/OpenMicrofrontendsRenderer';

/* TypeScript type from Schemas */

export interface Microfrontend1Config {
  welcomeMessage: string;
  [k: string]: unknown;
}

export interface Microfrontend1TopicPing {
  ping: true;
  [k: string]: unknown;
}

// Helper

function toFullUrl(...parts: Array<string>): string {
  return parts
    .filter((part, idx) => part && part.trim() && (idx === 0 || part !== '/'))
    .map((part) => (part.endsWith('/') ? part.slice(0, -1) : part))
    .map((part, idx) => (idx > 0 && part.startsWith('/') ? part.substring(1) : part))
    .join('/');
}

function addCssLinkTag(url: string, addedElements: Array<HTMLElement>): void {
  const linkElem = document.createElement('link');
  linkElem.rel = 'stylesheet';
  linkElem.href = url;
  linkElem.addEventListener('error', (error) => {
    console.error('[OpenMicrofrontends] Error loading CSS resource: ', url, error);
  });
  document.head.appendChild(linkElem);
  addedElements.push(linkElem);
}

declare var System: any;

function installSystemJSImportMap(initialModules: Array<string>, importMap: any) {
  if (!importMap.imports) {
    return;
  }
  const currentImportMap = System.getImportMap();
  const newImportMap = { imports: {}, scopes: {} };
  for (const _import in importMap.imports) {
    if (!currentImportMap.imports[_import]) {
      newImportMap.imports[_import] = importMap.imports[_import];
    } else if (currentImportMap.imports[_import] !== importMap.imports[_import]) {
      // Conflicting import map entries
      initialModules.forEach((moduleUrl) => {
        if (!(moduleUrl in newImportMap.scopes)) {
          newImportMap.scopes[moduleUrl] = {};
        }
        newImportMap.scopes[moduleUrl][_import] = importMap.imports[_import];
        // Also make sure conflicting entries only load modules from "their" import map
        newImportMap.scopes[importMap.imports[_import]] = {
          ...importMap.imports,
        };
      });
    }
  }
  System.addImportMap(newImportMap);
}

/* Asset query timestamp for cache busting */

const assetTimestamp = Math.floor(Date.now() / 10000) * 10;

/* Type Parameters */

type Microfrontend1Permissions = undefined;

type Microfrontend1MessagesPublish = Record<string, any>;
type Microfrontend1MessagesSubscribe = Record<string, any>;

/* Type-safe MessageBus slice for the client */

type Microfrontend1ClientMessageBus = {
  publish(topic: 'ping', data: Microfrontend1TopicPing): void;

  subscribe(topic: 'ping', cb: (data: Microfrontend1TopicPing) => void): void;
  unsubscribe(topic: 'ping', cb: (data: Microfrontend1TopicPing) => void): void;
};

/* Default config  */

const defaultConfig = {
  welcomeMessage: 'Hello World!',
};

/* Renderer context type with aligned config and message bus */

type Microfrontend1ClientContext = Omit<
  OpenMicrofrontendsClientContext<
    Partial<Microfrontend1Config>,
    Microfrontend1Permissions,
    undefined,
    Microfrontend1MessagesPublish,
    Microfrontend1MessagesSubscribe
  >,
  'apiProxyPaths' | 'serverSideRendered'
>;

/* Start function */

export async function startOpenMicrofrontendsExampleBrowserStandaloneSharedLibraries2(
  serverUrl: string,
  hostElement: HTMLElement,
  context: Microfrontend1ClientContext
) {
  const addedElements: Array<HTMLElement> = [];
  const exportedModules: Array<any> = [];

  const jsUrls = [toFullUrl(serverUrl, '/', `Microfrontend2.js?v=${assetTimestamp}`)];

  // Load initial modules consecutively (SystemJS)
  if (typeof System === 'undefined') {
    throw new Error(
      '[OpenMicrofrontends] Microfrontend "OpenMicrofrontends Example Browser Standalone Shared Libraries 2" requires SystemJS but is not available!'
    );
  }

  const initialModuleMapping = {};
  jsUrls.forEach((jsUrl) => {
    const moduleWithoutQuery = jsUrl.split('?')[0];
    initialModuleMapping[moduleWithoutQuery] = jsUrl;
  });
  const finalImportMap = {
    imports: {
      ...initialModuleMapping,

      ...{
        react: 'https://ga.system.jspm.io/npm:react@19.1.1/index.js',
        'react-dom': 'https://ga.system.jspm.io/npm:react-dom@19.1.1/index.js',
        'react-dom/client': 'https://ga.system.jspm.io/npm:react-dom@19.1.1/client.js',
        scheduler: 'https://ga.system.jspm.io/npm:scheduler@0.26.0/index.js',
        process: 'https://ga.system.jspm.io/npm:process@0.11.10/browser.js',
      },
    },
  };
  installSystemJSImportMap(jsUrls, finalImportMap);

  try {
    for (const jsUrl of jsUrls) {
      const module = await System.import(jsUrl);
      if (module) {
        exportedModules.push(module);
      }
    }
  } catch (e) {
    throw new Error(
      '[OpenMicrofrontends] Loading assets of Microfrontend "OpenMicrofrontends Example Browser Standalone Shared Libraries 2" failed!'
    );
  }

  const renderFunction =
    exportedModules.find((m) => 'startBrowserStandaloneSharedLibrariesMicrofrontend2' in m)?.[
      'startBrowserStandaloneSharedLibrariesMicrofrontend2'
    ] ||
    exportedModules.find((m) => 'default' in m && 'startBrowserStandaloneSharedLibrariesMicrofrontend2' in m.default)
      ?.default?.['startBrowserStandaloneSharedLibrariesMicrofrontend2'] ||
    (window as any)['startBrowserStandaloneSharedLibrariesMicrofrontend2'];
  if (!renderFunction) {
    throw new Error(
      '[OpenMicrofrontends] Renderer of Microfrontend "OpenMicrofrontends Example Browser Standalone Shared Libraries 2" not found!'
    );
  }

  const contextWithDefaultConfig = {
    ...context,
    config: {
      ...defaultConfig,
      ...context.config,
    },
  };

  // Render the Microfrontend
  console.info(
    '[OpenMicrofrontends] Starting Microfrontend "OpenMicrofrontends Example Browser Standalone Shared Libraries 2"'
  );
  const lifecycleHooks = await renderFunction(hostElement, contextWithDefaultConfig);

  return {
    close: async () => {
      console.info(
        '[OpenMicrofrontends] Closing Microfrontend "OpenMicrofrontends Example Browser Standalone Shared Libraries 2"'
      );
      await lifecycleHooks?.onRemove();
      addedElements.forEach((elem) => elem.remove());
      hostElement.innerHTML = '';
    },

    messages: context.messageBus as Microfrontend1ClientMessageBus,
  };
}
