/**
 * This file was automatically generated by OMG (OpenMicrofrontends Generator).
 * DO NOT MODIFY!
 */

import type { OpenMicrofrontendsRenderer } from '@open-microfrontends/types/OpenMicrofrontendsRenderer';

/* TypeScript type from Schemas */

export interface Microfrontend1Config {
  /**
   * The customer ID
   */
  customerId: string;
  [k: string]: unknown;
}

/* --- Microfrontend 1 --- */

/* Type Parameters */

export type Microfrontend1Permissions = undefined;

type Microfrontend1ApiProxyPaths = {
  readonly bff: string;
};

type Microfrontend1MessagesPublish = undefined;
type Microfrontend1MessagesSubscribe = undefined;

/* Renderer */

export type OpenMicrofrontendsExampleSSRRenderer = OpenMicrofrontendsRenderer<
  Microfrontend1Config,
  Microfrontend1Permissions,
  Microfrontend1ApiProxyPaths,
  Microfrontend1MessagesPublish,
  Microfrontend1MessagesSubscribe
>;

export const OpenMicrofrontendsExampleSSRRendererFunctionName = 'startSSRMicrofrontend';

/* Path constants */

export const OpenMicrofrontendsExampleSSRAssetsBasePath = '/';
