/**
 * This file was automatically generated by OMG (OpenMicrofrontends Generator).
 * DO NOT MODIFY!
 */

import type { OpenMicrofrontendsServerSideRendererFunction } from '@open-microfrontends/types/OpenMicrofrontendsServerSideRendererFunction';

/* TypeScript type from Schemas */

export interface Microfrontend1Config {
  /**
   * The customer ID
   */
  customerId: string;
  [k: string]: unknown;
}

/* --- Microfrontend 1 --- */

/* Type Parameters */

type Microfrontend1Permissions = undefined;

/* Render Function */

export type OpenMicrofrontendsExampleSSRServerSideRenderFunction = OpenMicrofrontendsServerSideRendererFunction<
  Microfrontend1Config,
  Microfrontend1Permissions
>;

/* Path constants */

export const OpenMicrofrontendsExampleSSRServerSideRenderPath = '/ssr';
