/**
 * This file was automatically generated by OMG (OpenMicrofrontends Generator).
 * DO NOT MODIFY!
 */

import type { OpenMicrofrontendsServerSideRenderer } from '@open-microfrontends/types/OpenMicrofrontendsServerSideRenderer';

/* TypeScript type from Schemas */

export interface Microfrontend1Config {
  /**
   * The customer ID
   */
  customerId: string;
  [k: string]: unknown;
}

/* --- Microfrontend 1 --- */

/* Type Parameters */

type Microfrontend1Permissions = undefined;

/* Renderer */

export type OpenMicrofrontendsExampleSSRServerSideRenderer = OpenMicrofrontendsServerSideRenderer<
  Microfrontend1Config,
  Microfrontend1Permissions
>;

/* Path constants */

export const OpenMicrofrontendsExampleSSRServerSideRendererPath = '/ssr';
