/**
 * This file was automatically generated by OMG (OpenMicrofrontends Generator).
 * DO NOT MODIFY!
 */

import type { OpenMicrofrontendsRenderer } from '@open-microfrontends/types/OpenMicrofrontendsRenderer';

/* TypeScript type from Schemas */

export interface Microfrontend1Config {
  welcomeMessage: string;
  [k: string]: unknown;
}

export interface Microfrontend1TopicPing {
  ping: true;
  [k: string]: unknown;
}

/* --- Microfrontend 1 --- */

/* Type Parameters */

export type Microfrontend1Permissions = undefined;

type Microfrontend1ApiProxyPaths = undefined;

type Microfrontend1MessagesPublish = {
  ping: Microfrontend1TopicPing;
};
type Microfrontend1MessagesSubscribe = {
  ping: Microfrontend1TopicPing;
};

/* Renderer */

export type OpenMicrofrontendsExampleBrowserStandaloneHelloWorldRenderer = OpenMicrofrontendsRenderer<
  Microfrontend1Config,
  Microfrontend1Permissions,
  Microfrontend1ApiProxyPaths,
  Microfrontend1MessagesPublish,
  Microfrontend1MessagesSubscribe
>;

export const OpenMicrofrontendsExampleBrowserStandaloneHelloWorldRendererFunctionName =
  'startBrowserStandaloneHelloWorldMicrofrontend';

/* Path constants */

export const OpenMicrofrontendsExampleBrowserStandaloneHelloWorldAssetsBasePath = '/';
